ARC fixes. closes #50
astellato/ofxSyphon pull request #52
Opened 2022-09-09 19:53 UTC by ofTheo

This is just the changes needed for ofxSyphon to work with ARC ( automatic reference counting ), which will be enabled on the next OF release ( and is already enabled in the nightly builds ). 

Confirmed working with the nightly downloads. 

Would love to get @2bbb and @danomatika 's take on this. 

Especially the way I am doing cleanup of the void pointers which we use for the client and server. 

https://github.com/astellato/ofxSyphon/compare/master...ofTheo:syphon-arc?expand=1#diff-ab7cfefbfb00d042e397c6984ba2f3f2d75db565a6a1e4e832a942891bd4f4d3R58-R63

NOTE: don't merge this to master until the next OF release.

2022-09-09 20:01 UTC, dimitre commented
I've just tested this one and everything seems to be working great!

2022-09-12 20:00 UTC, danomatika commented on src/ofxSyphonClient.mm
> +    //sketchy as we transfer ownership to void * and that means we have to manage the memory ourselves so in destructor we are going to make it back into an obj-c object and transfer back so ARC can
Different indentation.

2022-09-12 20:01 UTC, danomatika commented on src/ofxSyphonServer.h
> +    void cleanup();
Different indentation.

2022-09-12 20:01 UTC, danomatika commented on src/ofxSyphonServer.mm
> +        //sketchy as we transfer ownership to void * and that means we have to manage the memory ourselves so in destructor we are going to make it back into an obj-c object and transfer back so ARC
Different indentation.

2022-09-12 20:02 UTC, danomatika commented
Looks fine to me, other than a few indentation issues.

2022-09-13 01:41 UTC, ofTheo commented
Thanks @danomatika - I can fix the indentation stuff, only noticed it in the PR diff.

2022-09-16 03:26 UTC, ofTheo commented
@bangnoise - Thanks! 
I guess the void * is needed to avoid issues with including Obj-C includes from pure C++.

If there is a way around that, then the copy constructors, destructors etc wouldn't even be needed as with ARC all the objects would just maintain their own reference count. 

I don't know too much about auto release pools but looking at:
https://stackoverflow.com/questions/9086913/why-is-autoreleasepool-still-needed-with-arc 

It looks like it is useful when you want stuff to be released at the end of the function as opposed to at some point when the main autorelease pool decides. So maybe I could add back in @autorelease blocks to where the pools where before?

Anyway, def happy to have some extra eyes on this. 
@2bbb helped us with [our ARC transition](https://github.com/openframeworks/openFrameworks/pull/6889/files).

2022-09-16 08:55 UTC, danomatika commented
> It looks like it is useful when you want stuff to be released at the end of the function as opposed to at some point when the main autorelease pool decides. So maybe I could add back in @autorelease blocks to where the pools where before?

In full Obj-C projects, the main function has an autorelease pool basically wrapping everything, so ARC transitions there don't need any additional pools, as far as I remember. Here, though, we have our own C++ main without a pool, so I think you are right in that there needs to be one within these classes. I'm not an expert though, having learned Obj-C *thankfully* just as ARC was released. :)

2022-09-16 09:12 UTC, bangnoise requested changes
see in-line comments

2022-09-16 09:13 UTC, bangnoise commented
Apologies, I didn't press submit on my review, but GitHub confusingly shows my comments here (for me) before submitting. I meant the in-code comments to precede my last comment above - hopefully it makes a bit more sense now.

2022-09-16 11:21 UTC, bangnoise commented on src/ofxSyphonClient.mm
>  ofxSyphonClient::ofxSyphonClient(ofxSyphonClient const& s) :
I've done this in 4b82b56f7e20ed78832f1dbbd5a2fc579547dc53

2022-09-16 11:22 UTC, bangnoise commented on src/ofxSyphonClient.mm
> -    NSAutoreleasePool* pool = [[NSAutoreleasePool alloc] init];
I've restored the autorelease pools in 4b82b56f7e20ed78832f1dbbd5a2fc579547dc53

2022-09-16 11:23 UTC, bangnoise approved these changes

2022-09-16 11:34 UTC, bangnoise commented
I've added a basic wrapper C++ class which takes care of the NSObject lifetime - this fixes a lot of issues where ARC would lose track of objects we were storing in `void*` member variables, and makes `ofxSyphonServer` and `ofxSyphonClient` simpler - they no longer need custom copy and assignment operators.

I've restored the deleted autorelease pools so we don't leak Objective C objects when called from C++ code without an autorelease pool in place.

I've also updated the Xcode projects using a Project Generator from OF nightly.

2022-09-16 11:46 UTC, danomatika commented
@bangnoise Thanks for taking the time to integrate this. I see now that I also need to integrate pools within my PGMidi Obj-C class wrappers for ofxMidi...

2022-09-16 16:04 UTC, ofTheo commented
Hey @bangnoise, this approach looks great! 
Great to get rid of the void *.  Def makes the whole ARC approach less hack-y. 

I gave it a quick test and it all seems to work well. 
@dimitre maybe try pulling in these changes and see if you notice any issues with your setup?

2022-09-16 16:11 UTC, dimitre commented
I've just pulled fc94e9a and tested here in my setup, using syphon recorder and everything is working great here.
using 4 syphon outputs in this setup. 
<img width="360" alt="Screen Shot 2022-09-16 at 13 08 18" src="https://user-images.githubusercontent.com/58289/190682736-c87e15db-1dbd-4603-aaf9-aa5fcee30ea8.png">

2022-09-20 11:01 UTC, merged

2022-10-11 07:21 UTC, danomatika commented
PIMPL is a pretty well used idiom. I’d think ARC wouldn’t have a problem with it…

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com


> On Sep 15, 2022, at 7:14 PM, Tom Butterworth ***@***.***> wrote:
> 
> ﻿
> Thanks for this - it's a good start. Apart from removing all the autorelease pools, my main concern is re the breakage in assignment and copy operators noted above, and the fragility of storing NSObjects* in void* with ARC generally.
> ofxSyphonServer currently lacks assignment and copy operators, I'm about to add those, which will need the same solution for ARC.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.